## A little exercise to see whether you understand array manipulations.

    Follow the instructions in their correct order
    This means do 1 first before 2, and do 3 before 4.
    

## 1.  Declare a 6x6 array with all zeros
   Assign it to variable 'mm'

In [1]:
import numpy as np
mm = np.zeros ( (6,6) )
mm

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 2. Write '11' diagonally - from top left to bottom right

In [2]:
for i in range ( 6):
    mm[i][i]=11
mm

array([[11.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 11.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 11.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 11.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 11.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 11.]])

## 3. Write row of ‘33’ to row index 3


In [4]:
for j in range (6):
    mm[3][j]=3
mm

array([[11., 55., 55., 55., 55., 55.],
       [55., 11., 55., 55., 55., 55.],
       [55., 55., 11., 55., 55., 55.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [55., 55., 55., 55., 11., 55.],
       [55., 55., 55., 55., 55., 11.]])

## 4. Write ‘44’ to diagonal from bottom left to top right

In [6]:
for i in range (6):
    mm[i][5-i]=44
mm
#(0,5) (1,4) (2,3) ( 3,2) (4,1) (5,0)

array([[11., 55., 55., 55., 55., 44.],
       [55., 11., 55., 55., 44., 55.],
       [55., 55., 11., 44., 55., 55.],
       [ 3.,  3., 44.,  3.,  3.,  3.],
       [55., 44., 55., 55., 11., 55.],
       [44., 55., 55., 55., 55., 11.]])

## 5. Fill the empty cells with ‘55’


In [3]:
for i in range (6):
    for j in range (6):
        if (mm[i][j]==0):
            mm[i][j]=55
mm

array([[11., 55., 55., 55., 55., 55.],
       [55., 11., 55., 55., 55., 55.],
       [55., 55., 11., 55., 55., 55.],
       [55., 55., 55., 11., 55., 55.],
       [55., 55., 55., 55., 11., 55.],
       [55., 55., 55., 55., 55., 11.]])